### ISSUE TITLE
Should use require_dependency instead of require/load

### ISSUE THREAD

**Issue by elia** [solidusio/solidus_support#34]
https://github.com/solidusio/solidus_support/blob/master/lib/solidus_support/engine_extensions/decorators.rb#L31

`require_dependency` is the standard Rails way of requiring autoloadable (and thus reloadable) dependencies. The method has been around since forever and there's no backward compatibility problem.

See also this PR https://github.com/solidusio/solidus/pull/3008

**Comment by aldesantis** [comment]
I wonder if this is also a problem with Zeitwerk, considering that it overrides `Kernel#require`. Anyway, it would still be a problem worth fixing for Rails 5.2, so it makes total sense to me.

@elia happy to review a PR if you want to take a stab!
