### ISSUE TITLE
Release 0.5.2  version

### ISSUE THREAD

**Issue by jalkoby** [solidusio/solidus_support#64]
please push version 0.5.2 to rubygems

**Comment by jarednorman** [comment]
@kennyadsl Was there a reason that version never got pushed or was it yanked for some reason? I don't recall and it's not apparent to me from the git history.

**Comment by kennyadsl** [comment]
I can't recall, maybe it's just a mistake. @jalkoby May I ask why do you need that specific version?

**Comment by jalkoby** [comment]
Hi. I'm working on an old solidus project which we recently updated to rails 6. As the result zeitwerk was not happy about how decorators loaded. The first release which actually fix it is 0.5.2. The next version is 0.6.0 but we using solidus_social which locked for some reason on solidus_support "~> 0.4, < 0.6"

**Comment by kennyadsl** [comment]
Got it thanks, what if we update solidus_social instead?

**Comment by kennyadsl** [comment]
Oh, looks like it has been updated already: https://github.com/solidusio-contrib/solidus_social/blob/955dd479a73c4cef6e327cf37ef36ae5b67873fd/solidus_social.gemspec#L41. I will push a release for it today.

**Comment by kennyadsl** [comment]
@jalkoby [solidus_social 1.4.0 released](https://rubygems.org/gems/solidus_social). Let me know if we can close this one!

**Comment by jalkoby** [comment]
yes,  thanks
